//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.WorkItem = new HashSet<WorkItem>();
        }
    
        public System.Guid ProjectId { get; set; }
        public string Name { get; set; }
        public System.Guid LeaderId { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<WorkItem> WorkItem { get; set; }
    }
}
