//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Project = new HashSet<Project>();
            this.WorkItem = new HashSet<WorkItem>();
        }
    
        public System.Guid UserId { get; set; }
        public string Name { get; set; }
        public int RoleId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UserName { get; set; }
        public string Passwrod { get; set; }
    
        public virtual ICollection<Project> Project { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<WorkItem> WorkItem { get; set; }
    }
}
