//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeeklyReport.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItem
    {
        public System.Guid ItemId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid ProjectId { get; set; }
        public string Body { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> CreateUser { get; set; }
        public Nullable<System.Guid> UpdateUser { get; set; }
        public bool AllDay { get; set; }
        public double Duration { get; set; }
        public Nullable<long> End { get; set; }
        public Nullable<long> Start { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
