//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWeeklyReport.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Project = new HashSet<Project>();
            this.WorkItem = new HashSet<WorkItem>();
        }
    
        public System.Guid UserId { get; set; }
        public string Name { get; set; }
        public int RoleId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateData { get; set; }
    
        public virtual ICollection<Project> Project { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<WorkItem> WorkItem { get; set; }
    }
}
